name: Publish

on:
  push:
    branches:
      - latest

jobs:
  test:
    name: Check that the specification is correct
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.AUTH_TOKEN }}" > .npmrc

      - name: Dependencies installation
        run: npm install

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish --access public
